### ISSUE TITLE
Resource Not Found Exception

### ISSUE THREAD

**Issue by alimoeeny** [helloworldless/go-dynamodb-reference#1]
Hi, 
Thanks for sharing this code, 
I have been having a hard time make it work though, 
I get
> "https response error StatusCode: 400, RequestID: 800da01f-90ee-48a1-bd35-d4d0f6a9d061, ResourceNotFoundException: "

while at the same time a cli call works fine. 
Any pointers?

**Comment by alimoeeny** [comment]
I have not yet figured it out, but it must be a problem on my side.

**Comment by helloworldless** [comment]
I cleaned up the code and README a bit. Can you try it now?

**Comment by alimoeeny** [comment]
Thank you very much @helloworldless (cool name btw), 
I think my problems were:
- I didn't realize the order the functional `withX` calls matter. Like if you first call `withRegion` then call `WithEndpointResolverWithOptions` even if you don't provide a region in the second call it overwrites your region
- I didn't realize that local dynamodb respects the `ACCES_KEY` provided. I was making `aws cli` calls to create my tables and set things up then will run my go tests and the tests would fail with resource not found exceptions. The reason turned out to be the cli was using my cred from the aws/credentials file while go tests where using dummy credentials from the code (yeah in retrospect it is obvious)
